# Development compose file.

version: '2.3'
services:
  web:
    build:
      context: .
      target: base
    ports:
     - "127.0.0.1:8082:80"
    volumes:
     - .:/var/www/html
    links:
     - db
    environment:
     - ENVIRONMENT=DEV
     - DRUPAL_INSTALL=TRUE
     - HTPASSWD_USER
     - HTPASSWD_PASSWORD
     - SERVER_ADMIN
  db:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=docker
     - MYSQL_DATABASE=drupal
     - MYSQL_USER=drupal
     - MYSQL_PASSWORD=drupalpw
    volumes:
     - data:/var/lib/mysql
volumes:
  data: {}
