#!/bin/bash

COMMAND="export TERM=xterm && source ~www-data/xdebug.sh && drush $@"
echo -e "Executing inside container with xdebug support:\n\tdrush $@\n"
docker exec -ti -u www-data $(docker-compose ps -q web) bash -ci "$COMMAND"
